### ISSUE TITLE
Step 1 Issue

### ISSUE THREAD

**Issue by hcooch2ch3** [soleJin/ios-open-market#28]
Step 1 붱이 리뷰 및 이슈 정리

**Comment by soleJin** [comment]
1. HTTP Method 표준화?

**Comment by soleJin** [comment]
2.  static method와 singletone의 차이

**Comment by hcooch2ch3** [comment]
3. Moya의 Endpoint 의미

**Comment by hcooch2ch3** [comment]
4. OpenMarketAPI 메서드 세분화

>-  requst를 만들고
>- 네트워크 요청 하고
>- 디코드를 하는 것
까지 한 곳에서 하고 있네요
이부분을 아토믹하게 테스트할 수 있을까요?
더 잘게 쪼개야 각각을 테스트할 수 잇을것 같아요

**Comment by soleJin** [comment]
5. 네트워킹의 반복되는 코드 제네릭 + 리절트 타입 공부해서 적용해보기

> 반복되는 코드들이 눈에 보이네요
> 혹시 제네릭에 대해서 공부해볼까요?

**Comment by soleJin** [comment]
> 1. HTTP Method 표준화?
>    ![image](https://user-images.githubusercontent.com/28377820/106224242-4de40300-6226-11eb-8e93-5c017faa2cab.png)
> 
> -> RESTful
> [https://www.youtube.com/watch?v=ETdbm5jDDsg&t=18s](url)
